name: Deploy frontend (Streamlit) to Azure Web App - frontendP7

on:
  push:
    branches: [ "main" ]
    paths: [ "frontend/**" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v4
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: streamlit-app
          path: frontend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: streamlit-app

      # Solution la plus simple: Publish Profile (pas besoin d’un SP/AAD)
      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: frontendP7                  # ← nom exact de ton App Service frontend
          slot-name: production
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_FRONTEND }}
          package: .
